feat: enable manual triggering for deployment workflows and deployment varification

diff --git a/.github/workflows/deploy-to-development-server.yml b/.github/workflows/deploy-to-development-server.yml
--- a/.github/workflows/deploy-to-development-server.yml
+++ b/.github/workflows/deploy-to-development-server.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - development
+  workflow_dispatch:
 
 permissions:
   contents: read
@@ -36,3 +37,14 @@ jobs:
           DEV_DATABASE_PASSWORD: ${{ secrets.DEV_DATABASE_PASSWORD }}
           DEV_SUPERUSER_EMAIL: ${{ secrets.DEV_SUPERUSER_EMAIL }}
           DEV_SUPERUSER_PASSWORD: ${{ secrets.DEV_SUPERUSER_PASSWORD }}
+
+      - name: Verify deployment
+        run: |
+          echo "Waiting for services to start..."
+          sleep 10
+          if [ "$(docker ps -q -f name=backend)" ]; then
+            echo "✅ backend is running"
+          else
+            echo "❌ Failed to start backend"
+            exit 1
+          fi
diff --git a/.github/workflows/deploy-to-production-server.yml b/.github/workflows/deploy-to-production-server.yml
--- a/.github/workflows/deploy-to-production-server.yml
+++ b/.github/workflows/deploy-to-production-server.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+  workflow_dispatch:
 
 permissions:
   contents: read
@@ -38,3 +39,14 @@ jobs:
           PROD_SUPERUSER_EMAIL: ${{ secrets.PROD_SUPERUSER_EMAIL }}
           PROD_SUPERUSER_PASSWORD: ${{ secrets.PROD_SUPERUSER_PASSWORD }}
           PROD_ALLOWED_HOSTS: ${{ secrets.PROD_ALLOWED_HOSTS }}
+
+      - name: Verify deployment
+        run: |
+          echo "Waiting for services to start..."
+          sleep 10
+          if [ "$(docker ps -q -f name=backend)" ]; then
+            echo "✅ backend is running"
+          else
+            echo "❌ Failed to start backend"
+            exit 1
+          fi
